### ISSUE TITLE
Validation fails for link types in IssueVerified event

### ISSUE THREAD

**Issue by e-pettersson-ericsson** [eiffel-community/eiffel-remrem-generate#145]
### Description
REMReM generate does not accept the link types **FAILED_ISSUE, INCONCLUSIVE_ISSUE, or SUCCESSFUL_ISSUE** in the EiffelIssueVerifiedEvent.
The validation fails when adding those link types to an EiffelIssueVerifiedEvent, and gives the following error message:

```
{
  "message": "Cannot validate given JSON string",
  "cause": "com.ericsson.eiffel.remrem.semantics.validator.EiffelValidationException: FAILED_ISSUE,INCONCLUSIVE_ISSUE,SUCCESSFUL_ISSUE link types are invalid for the event EiffelIssueVerifiedEvent"
}
```

### Motivation
I expect REMReM to validate according to the protocol defined here: https://github.com/eiffel-community/eiffel/blob/master/eiffel-vocabulary/EiffelIssueVerifiedEvent.md .

The missing link types should be added to the IssueVerified event approved link types.

### Benefits
REMReM validates according to the protocol documentation.

### Possible Drawbacks
None.

**Comment by SantoshNC68** [comment]
Perhaps this validation is done in semantics, will move it to that repository
