### ISSUE TITLE
Missing doc update after PR 159

### ISSUE THREAD

**Issue by e-backmark-ericsson** [eiffel-community/eiffel-remrem-generate#163]
### Description
The documentation was not fully updated in #159. This page remains to be updated with the two new parameters: https://eiffel-community.github.io/eiffel-remrem-generate/serviceUsage.html

### Motivation
To get correct documentation

### Exemplification
-

### Benefits
Clarity

### Possible Drawbacks
-

**Comment by xsudban** [comment]
> ### Description
> The documentation was not fully updated in #159. This page remains to be updated with the two new parameters: https://eiffel-community.github.io/eiffel-remrem-generate/serviceUsage.html
> 
> ### Motivation
> To get correct documentation
> 
> ### Exemplification
> 
> ### Benefits
> Clarity
> 
> ### Possible Drawbacks

We have updated the documentation on master branch as part of code changes itself
can you please check.

The link you shared from gh-pages branch

**Comment by e-backmark-ericsson** [comment]
You mean this page: https://github.com/eiffel-community/eiffel-remrem-generate/blob/master/wiki/markdown/usage/service.md ?
If so, yes that seems to be fine. But please remove the https://eiffel-community.github.io/eiffel-remrem-generate/serviceUsage.html page since it is not up-to-date

**Comment by SantoshNC68** [comment]
Yes, we kept the github pages just for some templates that can be downloaded. Will try to remove the gh-pages soon.
